version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: visitors_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./gitignore/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"